# Generated by Django 5.1.2 on 2024-11-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.product')),
            ],
        ),
    ]
